services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    container_name: wp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wp-php
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      # Populate + share WordPress core from the built image
      - wordpress_core:/var/www/html
      # Mount plugin folder for development
      - ./wp-content/plugins/content-rebrand-tracker:/var/www/html/wp-content/plugins/content-rebrand-tracker:rw

  nginx:
    image: nginx:1.23-alpine
    container_name: wp-nginx
    depends_on:
      - wordpress
    ports:
      - "8000:80"
    volumes:
      # Mount shared WordPress core read-only
      - wordpress_core:/var/www/html:ro
      # Mount plugin folder for static assets
      - ./wp-content/plugins/content-rebrand-tracker:/var/www/html/wp-content/plugins/content-rebrand-tracker:ro
      # Nginx site configuration
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8080:80"

volumes:
  db_data:
    driver: local
  wordpress_core:
